backend:
    name: git-gateway
    branch: master
    repo: samwx/samuel-martins-v2
    site_domain: cms.netlify.com
    commit_messages:
        create: 'Create {{collection}} “{{slug}}”'
        update: 'Update {{collection}} “{{slug}}”'
        delete: 'Delete {{collection}} “{{slug}}”'
        uploadMedia: '[skip ci] Upload “{{path}}”'
        deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'content/posts'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      fields:
          - {
                label: 'Template Key',
                name: 'templateKey',
                widget: 'hidden',
                default: 'blog-post',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Publish Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Featured Image', name: 'featuredimage', widget: image, required: false }
          - { label: 'Featured image author', name: 'featuredimageauthor', widget: string, required: false }
          - { label: 'Featured image link', name: 'featuredimagelink', widget: string, required: false }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Tags', name: 'tags', widget: 'list' }

    - name: pages
      label: Pages
      files:
          - file: src/pages/index.md
            label: Home
            name: index
            fields:
                - {
                      label: Template Key,
                      name: templateKey,
                      widget: hidden,
                      default: index-page,
                  }
                - { label: Title, name: title, widget: string }
                - { label: Image, name: image, widget: image }
                - { label: Heading, name: heading, widget: string }
                - { label: Description, name: description, widget: string }
                - {
                    label: Social,
                    name: social,
                    widget: list,
                    fields: [
                        { label: Link, name: link, widget: string },
                        { label: Icon, name: icon, widget: image }
                    ]
                  }
          - file: src/pages/talks/index.md
            label: Talks
            name: talks
            fields:
                - {
                      label: Template Key,
                      name: templateKey,
                      widget: hidden,
                      default: talks-page,
                  }
                - { label: Title, name: title, widget: string }
                - {
                    label: Talks,
                    name: talksList,
                    widget: list,
                    fields: [
                        {
                            label: Title, name: talkTitle, widget: string
                        },
                        {
                            label: Description, name: talkDescription, widget: markdown
                        },
                        {
                            label: Link, name: talkLink, widget: string
                        }
                    ]
                }
          - file: src/pages/artigos/index.md
            label: Articles
            name: articles
            fields:
                - {
                        label: Template Key,
                        name: templateKey,
                        widget: hidden,
                        default: talks-page,
                  }
                - { label: Title, name: title, widget: string }
                - {
                    label: Articles,
                    name: articlesList,
                    widget: list,
                    fields: [
                        {
                            label: Title, name: articleTitle, widget: string
                        },
                        {
                            label: Description, name: articleDescription, widget: markdown
                        },
                        {
                            label: Link, name: articleLink, widget: string
                        }
                    ]
                }
